
import { LoadingProvider } from "@/providers/LoadingProvider";
import "./globals.css";
export const metadata = {
  title: "Mohit Vaishnav",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full overflow-x-hidden">
      <body className="h-full w-full oveflow-x-hidden">
        <LoadingProvider>
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
