"use client"
import { LoadingProvider } from "@/providers/LoadingProvider";
import { SmoothScrollProvider } from "@/providers/SmoothScrollProvider";
import "./globals.css";
import NavBar from "@/components/layouts/NavBar";
import { useState } from "react";
import MenuBar from "@/components/layouts/MenuBar";
import { Provider } from "react-redux";
import store from "@/store";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], display: "swap" });

// export const metadata = {
//   title: "Mohit Vaishnav",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <html lang="en" className="h-full w-full overflow-x-hidden">
      <body className={`h-full w-full overflow-x-hidden relative ${inter.className} ${menuOpen ? " overflow-hidden" : ""}`}>
        <SmoothScrollProvider>
          <Provider store={store}>
            <NavBar menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
            <MenuBar menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
            <LoadingProvider>
              {children}
            </LoadingProvider>
          </Provider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
