"use client"
import { LoadingProvider } from "@/providers/LoadingProvider";
import "./globals.css";
import NavBar from "@/components/layouts/NavBar";
import { useState } from "react";
import MenuBar from "@/components/layouts/MenuBar";
// export const metadata = {
//   title: "Mohit Vaishnav",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <html lang="en" className="h-full w-full overflow-x-hidden">
      <body className="h-full w-full oveflow-x-hidden bg-[#2B4854] relative">
        <NavBar menuOpen={menuOpen} setMenuOpen = {setMenuOpen}/>
        <MenuBar menuOpen={menuOpen} setMenuOpen = {setMenuOpen}/>
        <LoadingProvider>
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
